export const CartType = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    CART_ITEM: 'CART_ITEM',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    DELETE_ALL_ITEMS_FROM_CART: 'DELETE_ALL_ITEMS_FROM_CART',
}